swagger: "2.0"
info:
  title: Simple Booking Service
  description: From the todo list tutorial on goswagger.io
  version: 0.0.1
schemes:
  - http
paths: 
  /:
    get:
      responses:
          200:
            description: hello world
            schema:
              type: string
              default: hello world
  /books:
    get:
      parameters:
            - name: subject
              in: query
              type: string
      responses:
        200:
            description: list matching books
            schema:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                    minLength: 1
                  subjects:
                    type: array
                    items:
                      type: string
                  authors:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
        500:
            description: internal server error
            schema:
              $ref: "#/definitions/error"
  /bookings:
    post:
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: object
            properties:
              book_id:
                type: string
              quantity:
                type: integer
              book_at:
                type: integer
                format: unix timestamp
      responses:
          200:
            description: booking details
            schema:
              type: object
              properties:
                id:
                  type: integer
                book_id:
                  type: string
                quantity:
                  type: integer
                book_at:
                  type: integer
                  format: unix timestamp
                return_at:
                  type: integer
                  format: unix timestamp
          400:
            description: bad request
            schema:
              $ref: "#/definitions/error"
          404:
            description: book not found
            schema:
              $ref: "#/definitions/error"
          500:
            description: internal server error
            schema:
              $ref: "#/definitions/error"

definitions:
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
      message:
        type: string

    

